FROM zomorodiyan/openfoam10:mpich

ENV FOAM_INST_DIR=/opt/OpenFOAM \
    WM_PROJECT=OpenFOAM \
    WM_PROJECT_VERSION=10 \
    WM_PROJECT_DIR=/opt/OpenFOAM/OpenFOAM-10 \
    WM_PROJECT_USER_DIR=/home/openfoam/OpenFOAM/OpenFOAM-10 \
    HOME=/home/openfoam

SHELL ["/bin/bash", "-c"]

# Switch to OpenFOAM user
USER openfoam

# ✅ Confirm identity
RUN whoami && id && echo "HOME=$HOME"

# Clone and build laserbeamFoam
RUN git clone https://github.com/micmog/laserbeamFoam.git $HOME/laserbeamFoam && \
    cd $HOME/laserbeamFoam && \
    source $FOAM_INST_DIR/OpenFOAM-10/etc/bashrc && \
    ./Allwmake -j && \
    cp -v $HOME/OpenFOAM/-10/platforms/linux64GccDPInt32Opt/bin/laserbeamFoam $FOAM_INST_DIR/OpenFOAM-10/platforms/linux64GccDPInt32Opt/bin/ && \
    cp -v $HOME/OpenFOAM/-10/platforms/linux64GccDPInt32Opt/lib/liblaserHeatSource.so $FOAM_INST_DIR/OpenFOAM-10/platforms/linux64GccDPInt32Opt/lib/

RUN chmod -R a+rX $HOME/laserbeamFoam
RUN echo "source $FOAM_INST_DIR/OpenFOAM-10/etc/bashrc" >> $HOME/.bashrc

WORKDIR /home/openfoam

